# Generated by Django 5.2 on 2026-03-30 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cloud_engineer', 'Cloud Engineer'), ('devops_engineer', 'DevOps Engineer'), ('solutions_architect', 'Solutions Architect'), ('sre', 'Site Reliability Engineer'), ('cloud_security', 'Cloud Security Engineer'), ('data_engineer', 'Data Engineer'), ('backend_developer', 'Backend Developer'), ('fullstack_developer', 'Full Stack Developer'), ('ml_engineer', 'ML Engineer'), ('platform_engineer', 'Platform Engineer')], max_length=50)),
                ('difficulty', models.CharField(choices=[('fresher', 'Fresher'), ('junior', 'Junior (1-2 yrs)'), ('mid', 'Mid-Level (3-5 yrs)'), ('senior', 'Senior (5+ yrs)'), ('lead', 'Lead / Principal')], default='junior', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('bot', 'Bot'), ('user', 'User')], max_length=10)),
                ('content', models.TextField()),
                ('is_question', models.BooleanField(default=False)),
                ('is_feedback', models.BooleanField(default=False)),
                ('answer_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('incorrect', 'Incorrect')], default='', max_length=20)),
                ('ideal_answer', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(default=0, help_text='Score out of 10 for this answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interview.interviewsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
