# Generated by Django 5.2 on 2026-03-26 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Max lab duration in minutes')),
                ('max_score', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('terraform_dir', models.CharField(default='Terraform/IAM', help_text='Relative path to the Terraform config directory', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('submitted', 'Submitted'), ('ended', 'Ended'), ('expired', 'Expired')], default='provisioning', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('credentials_received_at', models.DateTimeField(blank=True, null=True)),
                ('timer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('iam_user_name', models.CharField(blank=True, default='', max_length=100)),
                ('console_password', models.CharField(blank=True, default='', max_length=100)),
                ('console_login_link', models.URLField(blank=True, default='')),
                ('terraform_state', models.CharField(choices=[('none', 'None'), ('applying', 'Applying'), ('applied', 'Applied'), ('destroying', 'Destroying'), ('destroyed', 'Destroyed'), ('error', 'Error')], default='none', max_length=20)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Lab.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LabScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.IntegerField(default=0)),
                ('passed_tasks', models.IntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Lab.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_scores', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='Lab.labsession')),
            ],
            options={
                'ordering': ['-scored_at'],
            },
        ),
        migrations.CreateModel(
            name='LabActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True, default='')),
                ('is_passed', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Raw validation details from boto3')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Lab.labsession')),
            ],
            options={
                'verbose_name_plural': 'Lab Activities',
                'ordering': ['checked_at'],
            },
        ),
    ]
