# Generated by Django 4.2.30 on 2026-04-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='cpu_limit',
            field=models.FloatField(default=0.5, help_text='CPU core limit for the container'),
        ),
        migrations.AddField(
            model_name='lab',
            name='docker_image',
            field=models.CharField(default='ubuntu:22.04', help_text='Docker image to use for docker labs', max_length=200),
        ),
        migrations.AddField(
            model_name='lab',
            name='enable_network',
            field=models.BooleanField(default=True, help_text='Provide internet access to the container'),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('docker', 'Docker'), ('aws', 'AWS')], default='aws', max_length=20),
        ),
        migrations.AddField(
            model_name='lab',
            name='memory_limit',
            field=models.CharField(default='256m', help_text='Memory limit for the container', max_length=20),
        ),
        migrations.AddField(
            model_name='labsession',
            name='container_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labsession',
            name='container_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labsession',
            name='container_state',
            field=models.CharField(choices=[('none', 'None'), ('creating', 'Creating'), ('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('error', 'Error')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='labsession',
            name='selected_duration',
            field=models.IntegerField(choices=[(15, '15 Minutes'), (30, '30 Minutes'), (45, '45 Minutes'), (60, '60 Minutes')], default=30, help_text='User-selected duration in minutes'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='terraform_dir',
            field=models.CharField(default='Terraform/IAM', help_text='Relative path to the Terraform config directory (for aws labs)', max_length=300),
        ),
        migrations.CreateModel(
            name='LabQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('task', 'Task')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('points', models.IntegerField(default=10)),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_option', models.CharField(blank=True, max_length=1)),
                ('task_instructions', models.TextField(blank=True)),
                ('validation_command', models.TextField(blank=True, help_text='Shell command to verify task completion')),
                ('expected_output', models.TextField(blank=True, help_text='Expected output pattern (regex supported)')),
                ('hint', models.TextField(blank=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Lab.lab')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LabAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.labquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Lab.labsession')),
            ],
        ),
    ]
