# Generated by Django 4.2.30 on 2026-04-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0002_lab_cpu_limit_lab_docker_image_lab_enable_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='assigned_questions',
            field=models.JSONField(blank=True, default=list, help_text='List of LabQuestion IDs assigned to this session'),
        ),
    ]
