# Generated by Django 4.2.30 on 2026-04-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0003_labsession_assigned_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labquestion',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='cpu_limit',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='docker_image',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='enable_network',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='lab_type',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='memory_limit',
        ),
        migrations.RemoveField(
            model_name='labsession',
            name='assigned_questions',
        ),
        migrations.RemoveField(
            model_name='labsession',
            name='container_id',
        ),
        migrations.RemoveField(
            model_name='labsession',
            name='container_name',
        ),
        migrations.RemoveField(
            model_name='labsession',
            name='container_state',
        ),
        migrations.RemoveField(
            model_name='labsession',
            name='selected_duration',
        ),
        migrations.AlterField(
            model_name='lab',
            name='terraform_dir',
            field=models.CharField(default='Terraform/IAM', help_text='Relative path to the Terraform config directory', max_length=300),
        ),
        migrations.DeleteModel(
            name='LabAnswer',
        ),
        migrations.DeleteModel(
            name='LabQuestion',
        ),
    ]
