# Generated by Django 4.2.30 on 2026-04-28 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0004_remove_labquestion_lab_remove_lab_cpu_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('overview', models.TextField(help_text='Brief overview of what this material covers')),
                ('icon', models.CharField(default='menu_book', help_text='Material icon name', max_length=50)),
                ('estimated_read_minutes', models.IntegerField(default=15)),
                ('prerequisites', models.TextField(blank=True, default='', help_text='Prerequisite knowledge (one per line)')),
                ('learning_outcomes', models.TextField(blank=True, default='', help_text='Learning outcomes (one per line)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_material', to='Lab.lab')),
            ],
            options={
                'verbose_name_plural': 'Study Materials',
            },
        ),
        migrations.CreateModel(
            name='StudySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('section_type', models.CharField(choices=[('theory', 'Theory'), ('concept', 'Concept'), ('architecture', 'Architecture'), ('best_practice', 'Best Practice'), ('hands_on', 'Hands-On Guide'), ('reference', 'Reference')], default='theory', max_length=20)),
                ('content', models.TextField(help_text='Main content in HTML/markdown')),
                ('code_example', models.TextField(blank=True, default='', help_text='Optional code snippet/CLI example')),
                ('code_language', models.CharField(blank=True, default='bash', help_text='Language for syntax highlighting', max_length=30)),
                ('tip', models.TextField(blank=True, default='', help_text='Pro tip or important note')),
                ('key_takeaway', models.TextField(blank=True, default='', help_text='Key takeaway summary')),
                ('icon', models.CharField(default='article', help_text='Material icon name', max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Lab.studymaterial')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('material', 'order')},
            },
        ),
    ]
