# Generated by Django 4.2.30 on 2026-04-21 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('scenario', models.TextField(help_text='Backstory/scenario for the lab')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_minutes', models.IntegerField(default=30, help_text='Max lab duration in minutes')),
                ('docker_image', models.CharField(default='cloudlabx-linux-lab:latest', help_text='Docker image to use for this lab', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(default='terminal', help_text='Material icon name', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalLabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('expired', 'Expired')], default='active', max_length=20)),
                ('container_id', models.CharField(blank=True, default='', max_length=100)),
                ('current_challenge_order', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('timer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='linux_labs.terminallab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_lab_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('question_text', models.TextField(help_text='The scenario/question presented to the user')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], help_text='Correct MCQ answer', max_length=1)),
                ('expected_commands', models.JSONField(default=list, help_text='List of command patterns (regex) that must appear in terminal history')),
                ('command_hint', models.TextField(blank=True, default='', help_text='Hint shown after wrong attempt')),
                ('points', models.IntegerField(default=10)),
                ('explanation', models.TextField(blank=True, default='', help_text='Explanation shown after submission')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='linux_labs.terminallab')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lab', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, default='', max_length=1)),
                ('is_mcq_correct', models.BooleanField(default=False)),
                ('command_history', models.JSONField(default=list, help_text='Commands the user ran in the terminal')),
                ('is_commands_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='linux_labs.terminalchallenge')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='linux_labs.terminallabsession')),
            ],
            options={
                'ordering': ['challenge__order'],
                'unique_together': {('session', 'challenge')},
            },
        ),
    ]
